services:
  server:
    restart: unless-stopped
    image: 192.168.1.160:5000/neuron-server:latest
    build: .

  db:
    restart: unless-stopped
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=neuron
      - POSTGRES_USER=neuron

  # riza:
  #   restart: unless-stopped
  #   image: rizaio/code-interpreter
  #   environment:
  #     - RIZA_API_KEY=${RIZA_API_KEY}
  #     - RIZA_LICENSE_KEY=${RIZA_LICENSE_KEY}

  neo4j:
    restart: unless-stopped
    image: neo4j:5.26.0

  redis:
    restart: unless-stopped
    image: redis:7.4-alpine
