services:
  server:
    env_file:
      - .env-docker
    ports:
      - 4449:5000
    volumes:
      - ./static:/neuron/static
      - ./src/neuron_client:/app/src/neuron_client
      - ./src/neuron_server:/app/src/neuron_server

  db:
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env-docker
    volumes:
      - database-data:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  database-data:
  redis-data:
