FROM python:3.12-slim

RUN apt-get update && apt-get install -yqq \
  texlive-latex-base \
  texlive-latex-extra \
  texlive-fonts-recommended \
  dvipng \
  && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python -m venv /venv && \
  /venv/bin/python -m pip install \
  numpy \
  matplotlib \
  pandas \
  seaborn[stats] \
  scipy \
  statsmodels \
  SciencePlots \
  adjustText \
  plotnine[all] \
  plotly \
  kaleido \
  astroplan \
  astropy \
  starplot \
  pillow

WORKDIR /app

RUN useradd -m code -d /app

USER code

ENV PATH="/venv/bin:$PATH"
ENV LANG="C.UTF-8"
ENV LC_ALL="C.UTF-8"
ENV PYTHONIOENCODING="utf-8"
ENV MPLCONFIGDIR="/app"

ENTRYPOINT [ "/venv/bin/python" ]

