FROM python:3.12-slim

RUN apt-get update && apt-get install -yqq \
  texlive-latex-base \
  texlive-latex-extra \
  texlive-fonts-recommended \
  dvipng \
  cm-super \
  && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python -m venv /venv && \
  /venv/bin/python -m pip install \
  numpy \
  matplotlib \
  pandas \
  seaborn[stats] \
  scipy \
  statsmodels \
  SciencePlots \
  adjustText \
  plotnine[all] \
  plotly \
  kaleido \
  astroplan \
  astropy \
  starplot \
  pillow \
  opencv-python-headless

WORKDIR /app

RUN useradd -m code -d /app && chown -R code /app

USER code

ENV PATH="/venv/bin:$PATH"
ENV LANG="C.UTF-8"
ENV LC_ALL="C.UTF-8"
ENV PYTHONIOENCODING="utf-8"
ENV MPLCONFIGDIR="/app"
ENV HOME="/app"

RUN /venv/bin/python -c "from astropy.utils.data import download_file; \
  urls = [ \
  'https://data.nanograv.org/static/data/ephem/de405.bsp', \
  'https://data.nanograv.org/static/data/ephem/de430t.bsp', \
  ]; \
  [download_file(url, cache=True) for url in urls]"

ENTRYPOINT [ "/venv/bin/python" ]

