services:
  server:
    image: 192.168.1.160:5000/neuron-server:latest
    build: .

  db:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=neuron
      - POSTGRES_USER=neuron

  redis:
    image: redis:7.4-alpine
