services:
  client:
    ports:
      - 4449:80
    volumes:
      - ./src/neuron_client/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  server:
    env_file:
      - .env-docker
    environment:
      - SERVE_CLIENT=true
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_URL=bolt://neo4j:7687
    ports:
      - 5000:5000
    volumes:
      - static-data:/app/static
      - ./src/neuron_server:/app/src/neuron_server

  db:
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env-docker
    volumes:
      - database-data:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  neo4j:
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/config:/config
    env_file:
      - .env-docker

  # riza:
  #   restart: unless-stopped
  #   ports:
  #     - 3003:3003

volumes:
  database-data:
  redis-data:
  neo4j-data:
  static-data:
