FROM python:3.12-slim

RUN apt-get update && apt-get install -yq \
  texlive-latex-base \
  texlive-latex-extra \
  texlive-fonts-recommended \
  texlive-science \
  texlive-pictures \
  latexmk \
  dvipng \
  cm-super \
  ffmpeg \
  && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python -m venv /venv && \
  /venv/bin/python -m pip install \
  astroplan==0.10.1 \
  astropy==7.0.0 \
  kaleido==0.2.1 \
  matplotlib==3.10.0 \
  numpy==2.2.1 \
  opencv-python-headless==4.10.0.84 \
  pandas==2.2.3 \
  pillow==11.0.0 \
  plotly==5.24.1 \
  scienceplots==2.1.1 \
  scipy==1.14.1 \
  seaborn[stats]==0.13.2 \
  statsmodels==0.14.4 \
  jplephem==2.22 \
  pylatex==1.4.2

WORKDIR /app

RUN useradd -m code -d /app && chown -R code /app

USER code

ENV PATH="/venv/bin:$PATH"
ENV LANG="C.UTF-8"
ENV LC_ALL="C.UTF-8"
ENV PYTHONIOENCODING="utf-8"
ENV MPLCONFIGDIR="/app"
ENV HOME="/app"

RUN /venv/bin/python -c "from astropy.utils.data import download_file; \
  urls = [ \
  'https://data.nanograv.org/static/data/ephem/de405.bsp', \
  'https://data.nanograv.org/static/data/ephem/de430t.bsp', \
  ]; \
  [download_file(url, cache=True) for url in urls]"

ENTRYPOINT [ "/venv/bin/python" ]

