services:
  # Optional: Remove or comment out the client service if you set SERVE_CLIENT=true on the server
  client:
    restart: unless-stopped
    image: gitea.zaks.io/isuttell/neuron-client:latest
    build:
      context: .
      dockerfile: Dockerfile.client

  server:
    restart: unless-stopped
    image: gitea.zaks.io/isuttell/neuron-server:latest
    build: .

  db:
    restart: unless-stopped
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=neuron
      - POSTGRES_USER=neuron
  neo4j:
    restart: unless-stopped
    image: neo4j:5.26.0

  redis:
    restart: unless-stopped
    image: redis:7.4-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  redis-data:
