[tool.poetry]
name = "neuron_server"
version = "0.1.0"
description = ""
authors = ["Isaac Suttell <isaac@isaacsuttell.com>"]

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "*"
huggingface_hub = "*"
opencv-python-headless = "*"
pillow = "*"
pydantic = "*"
quart = "*"
hypercorn = "*"
langchain = "0.3.17"
langgraph = "0.2.69"
langchain_openai = "0.3.3"
langchain_community = "0.3.16"
langchain_anthropic = "0.3.5"
langchain_postgres = "*"
langchain-cohere = "0.4.2"
langgraph-checkpoint-postgres = "2.0.13"
langchain-text-splitters = "0.3.5"
langsmith = "*"
aiohttp = "*"
arxiv = "*"
pymupdf4llm = "*"
pymupdf = "1.24.14"
elevenlabs = "*"
sqlalchemy = { version = "*", extras = ["asyncio"] }
psycopg = { version = "3.2.3", extras = ["binary", "pool"] }
psycopg-pool = "*"
redis = { version = "*", extras = ["hiredis"] }
skyfield = "*"
pandas = "*"
astroquery = "*"
wikipedia = "*"
astropy = "*"
pyvo = "*"
astroplan = "*"
matplotlib = "*"
tabulate = "*"
starplot = "*"
wolframalpha = "*"
RestrictedPython = "*"
langchain_neo4j = "*"
neo4j = "*"
firecrawl-py = "*"
replicate = "*"
aiofiles = "*"
piexif = "*"
yt-dlp = "*"
pyjwt = { version = "*", extras = ["crypto"] }
lxml = "*"
pi-heif = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-asyncio = "*"
ruff = "^0.9.3"
black = "^25.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


# Assume Python 3.11
target-version = "py311"

# Enable auto-fixes
fix = true

[tool.ruff.lint]
# Enable pycodestyle, Pyflakes, isort, and more
select = ["E", "F", "I", "N", "UP", "ANN", "B", "A", "C4", "RET", "SIM", "ERA", "PL"]
ignore = []
extend-select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["neuron_server"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"] # Ignore unused imports in __init__.py files

[tool.ruff.lint.pydocstyle]
convention = "google"
