name: Neuron Server PR Build

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'package.json'
      - 'package-lock.json'
      - '.gitea/workflows/neuron-server-pr-build.yml'

jobs:
  build-neuron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Calculate Dockerfile hash
        id: dockerfile-hash
        run: echo "hash=$(sha256sum Dockerfile | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          install: true

# Docker driver with buildx uses its own internal caching mechanism

      - name: Build image
        id: build-only
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          load: true
          tags: gitea.zaks.io/isuttell/neuron:pr-${{ github.event.pull_request.number }}
