name: Neuron Server PR Build

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'package.json'
      - 'package-lock.json'
      - '.gitea/workflows/neuron-server-pr-build.yml'

jobs:
  build-neuron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Calculate Dockerfile hash
        id: dockerfile-hash
        run: echo "hash=$(sha256sum Dockerfile | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Docker layer caching
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-pr-${{ steps.dockerfile-hash.outputs.hash }}-${{ github.event.pull_request.number }}
          restore-keys: |
            ${{ runner.os }}-docker-pr-${{ steps.dockerfile-hash.outputs.hash }}-
            ${{ runner.os }}-docker-pr-

      - name: Build image
        id: build-only
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: gitea.zaks.io/isuttell/neuron:pr-${{ github.event.pull_request.number }}
