"""Initial migration with all tables

Revision ID: 5f47b64a7a1f
Revises:
Create Date: 2025-06-26 15:01:58.017056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f47b64a7a1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add index on threads.updated_at for better performance when sorting threads
    op.create_index('ix_threads_updated_at', 'threads', ['updated_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the threads.updated_at index
    op.drop_index('ix_threads_updated_at', table_name='threads')
    # ### end Alembic commands ###
