"""add status field to personality_rooms

Revision ID: 77ea140e8a7c
Revises: dcbf3cb8d94b
Create Date: 2025-07-27 12:07:06.534002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77ea140e8a7c'
down_revision: Union[str, Sequence[str], None] = 'dcbf3cb8d94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personality_rooms', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personality_rooms', 'status')
    # ### end Alembic commands ###
