"""add personality rooms and update personality messages

Revision ID: dcbf3cb8d94b
Revises: 46dd00469c1e
Create Date: 2025-07-27 09:36:05.862356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcbf3cb8d94b'
down_revision: Union[str, Sequence[str], None] = '46dd00469c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personality_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personality_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personality_rooms_created_by'), 'personality_rooms', ['created_by'], unique=False)
    op.create_index(op.f('ix_personality_rooms_personality_id'), 'personality_rooms', ['personality_id'], unique=False)
    op.create_table('personality_room_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personality_room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['personality_room_id'], ['personality_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personality_room_id', 'user_id', name='unique_personality_room_user')
    )
    op.create_index(op.f('ix_personality_room_users_personality_room_id'), 'personality_room_users', ['personality_room_id'], unique=False)
    op.create_index(op.f('ix_personality_room_users_user_id'), 'personality_room_users', ['user_id'], unique=False)
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')

    # Add columns as nullable first to handle existing data
    op.add_column('personality_messages', sa.Column('personality_room_id', sa.UUID(), nullable=True))
    op.add_column('personality_messages', sa.Column('thread_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_personality_messages_personality_room_id'), 'personality_messages', ['personality_room_id'], unique=False)
    op.create_index(op.f('ix_personality_messages_thread_id'), 'personality_messages', ['thread_id'], unique=False)
    op.create_foreign_key(None, 'personality_messages', 'personality_rooms', ['personality_room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'personality_messages', 'threads', ['thread_id'], ['id'], ondelete='SET NULL')

    # Create default rooms for existing personalities with messages and update messages
    op.execute("""
        -- Create a default room for each personality that has messages
        INSERT INTO personality_rooms (id, personality_id, name, type, message_count, created_by)
        SELECT
            gen_random_uuid(),
            pm.personality_id,
            'Default Room',
            'shared',
            COUNT(*),
            NULL
        FROM personality_messages pm
        WHERE pm.personality_room_id IS NULL
        GROUP BY pm.personality_id;

        -- Update existing messages to belong to the default room
        UPDATE personality_messages pm
        SET personality_room_id = pr.id
        FROM personality_rooms pr
        WHERE pm.personality_id = pr.personality_id
        AND pr.name = 'Default Room'
        AND pm.personality_room_id IS NULL;
    """)

    # Now make personality_room_id non-nullable
    op.alter_column('personality_messages', 'personality_room_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personality_messages', type_='foreignkey')
    op.drop_constraint(None, 'personality_messages', type_='foreignkey')
    op.drop_index(op.f('ix_personality_messages_thread_id'), table_name='personality_messages')
    op.drop_index(op.f('ix_personality_messages_personality_room_id'), table_name='personality_messages')
    op.drop_column('personality_messages', 'thread_id')
    op.drop_column('personality_messages', 'personality_room_id')
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.drop_index(op.f('ix_personality_room_users_user_id'), table_name='personality_room_users')
    op.drop_index(op.f('ix_personality_room_users_personality_room_id'), table_name='personality_room_users')
    op.drop_table('personality_room_users')
    op.drop_index(op.f('ix_personality_rooms_personality_id'), table_name='personality_rooms')
    op.drop_index(op.f('ix_personality_rooms_created_by'), table_name='personality_rooms')
    op.drop_table('personality_rooms')
    # ### end Alembic commands ###
