"""Type definitions for tool artifacts - supplemental to markdown content."""

import xml.etree.ElementTree as ET
from typing import Literal

from pydantic import BaseModel, Field


class ToolArtifactMetadata(BaseModel):
    """Metadata for tool-generated content."""

    model: str | None = Field(default=None, description="Model used for generation")
    seed: int | None = Field(default=None, description="Random seed")
    prompt: str | None = Field(default=None, description="Original prompt")
    revised_prompt: str | None = Field(
        default=None, description="Model's revised prompt"
    )

    # Image-specific
    aspect_ratio: str | None = None
    quality: str | None = None
    style: str | None = None
    image_id: str | None = None  # OpenAI multi-turn ID

    # Audio/Video-specific
    duration: float | None = None
    cfg_strength: float | None = None
    num_steps: int | None = None
    num_inference_steps: int | None = None
    negative_prompt: str | None = None
    audio_added: bool | None = None  # For video with audio

    # Output format
    output_format: str | None = None
    background: str | None = None

    class Config:
        extra = "allow"  # Allow additional fields for extensibility


class ToolMediaItem(BaseModel):
    """A media item generated by a tool."""

    id: str = Field(description="Media item ID from database")
    url: str = Field(description="URL to access the media")
    caption: str = Field(description="Short caption/name for display")
    description: str = Field(default="", description="Detailed description")
    prompt_comparison: str | None = Field(
        default=None, description="How the generated result differs from the prompt"
    )
    metadata: ToolArtifactMetadata = Field(
        default_factory=ToolArtifactMetadata, description="Generation metadata"
    )


class ToolMediaArtifact(BaseModel):
    """Artifact containing media items for UI display."""

    type: Literal["media"] = "media"
    media_type: Literal["image", "audio", "video", "html", "code", "data"] = Field(
        description="Type of content"
    )
    items: list[ToolMediaItem] = Field(description="List of generated media items")

    def to_xml(self) -> str:
        """Generate XML representation for LLM consumption using ElementTree."""
        if len(self.items) == 1:
            # Single item
            item = self.items[0]
            root = ET.Element(self.media_type)

            # Add basic fields
            ET.SubElement(root, "id").text = item.id
            ET.SubElement(root, "url").text = item.url
            ET.SubElement(root, "caption").text = item.caption

            # Add optional fields
            if item.description:
                ET.SubElement(root, "description").text = item.description
            if item.prompt_comparison:
                ET.SubElement(root, "prompt_comparison").text = item.prompt_comparison
            if self.media_type in ("audio", "video") and item.metadata.duration:
                ET.SubElement(root, "duration").text = str(item.metadata.duration)
            if item.metadata.audio_added:
                ET.SubElement(root, "audio_added").text = "true"

        else:
            # Multiple items
            root = ET.Element(f"{self.media_type}s")
            for item in self.items:
                item_elem = ET.SubElement(root, self.media_type)

                # Add basic fields
                ET.SubElement(item_elem, "id").text = item.id
                ET.SubElement(item_elem, "url").text = item.url
                ET.SubElement(item_elem, "caption").text = item.caption

                # Add optional fields
                if item.description:
                    ET.SubElement(item_elem, "description").text = item.description
                if item.prompt_comparison:
                    ET.SubElement(
                        item_elem, "prompt_comparison"
                    ).text = item.prompt_comparison
                if self.media_type in ("audio", "video") and item.metadata.duration:
                    ET.SubElement(item_elem, "duration").text = str(
                        item.metadata.duration
                    )
                if item.metadata.audio_added:
                    ET.SubElement(item_elem, "audio_added").text = "true"

        return ET.tostring(root, encoding="unicode")
